sudo: required

services:
  - docker

env:
  global:
    - DOCKER_HUB_USER=vardantandon
    # DOCKER_HUB_PASSWORD
    - secure: Cn6fz6PXudOpLsWVtAE6mwEmRq55Tpvw1kjZ/a9qzsXk0QKqhpFVETxXJlj8Cfp5pQmJAxNs3HLMgO3OASXuHeDX2GZtQLYFitA4hanaznu3n5pSPK19gopzfxhaYvZ/bj9sNido/quykBzQf9kqKmnRCZgP4dSpGs+KYqc0DwXgd/vm83iBqe7DmbMGEYqz3cpgp7oPW/dShdIRrE/vyiDhdtCwBhJRq7qQk5jrc0xzirrtFp52L2vSeOhixRBlGGNwk90qEvHs/bUgagE07cjci29w58uNpUD69d23cftsQsnY2/upe9Z8ccwsVTbbi0eM2m5C1dqti8g5J0wzO0LFr23byS8G9nISLAMgalp1nlNXg/cOO8clJW6i7FVEZxnhzyQLGAc97IZM+c9Z/vir3+38M8QWDShzftse4/iQp4YpAxkiQeOPEUYWolmFVZw/nZ9Aima9LaLsnzr3LfAPZhAMxKobWp6wNfe5f3uDZZ5xUVLlQbJQYB/YbNcRR1qq95WukqQYE0meKWgx8sJJBCm0Rpm9YvUTyJchByP/ieX1XpCxK8BGUyhuUpV1OZlkIU/anVt2JYhjfsKzDeilSu9iA2buX6GIhvFOHzDeTWVe+wE/O5xiOoOY4zzDkr12t3E09lI+53nwFn2kB+APbDaMGHiz7ttvfjxlIbw=


script:
  - docker build -t vardantandon/docker-node-travis-example .
  - docker images vardantandon/docker-node-travis-example

before_deploy:
  - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"

deploy:
  provider: script
  script: docker push vardantandon/docker-node-travis-example
  on:
    branch: master
