sudo: required
services:
  - docker
env:
  global:
    - DOCKER_HUB_USER=vardantandon
    # DOCKER_HUB_PASSWORD
    - secure: NwaVDn6Bwkk21u9URYq19f5U0wmAZJb6pTpXQLa88FXNl8Al9TwxeFKAlR0Qn4uhoLsZfQIg8DLmTF9fDFekcNwrqWbcL78jS4ugepihZniZBGa73xAIkuL7kh2/D6sdDX4znTOnPW9IwGUiltWp4F7omVQHBQELoPwmXsALOLo21lS/VmGqfeTomCY2wB0oaDQdAVBZpvVm4O3MCYSqWo6GMN8esETZ0RL9M4wG+ABFDTbBIwZ0ztO6uZZKmzFoX8IksPx1XiUkrwfqNX+U5/Wp2Kd0Rg6sXfvGoeCFHaEzq3BVPtXUE6RxGkVyjB3VWeoIdw913lRPW9nRPTOHXPkcJ3V81Ts2VE0r+zV2KE9I96BmKqOzASrICPSiivLXFBPrGnDB+VdRSc3j2L7KbdhdQfjvwz9B83G5KTqJTPa5IPy0ou/dmSIeNTNw4nmA7CosFvIXkmA7Mr8Ctv4kGby9sNLqdyrDCDv2x9Omh2kSn67U+W9/a1onrj18blK2jSAQht+/uuBQMQbLuNiyjbsxUIeUviZjQGjHd9Im0lSjBRUwe83AND+kCr6HG4drGT9MxRPsqLW1UPgwu6320V8v4DyHl8v0KCF98fWcxPyPwADCWO8phikEVoMfzXBSsLSpJdM96o2/wuug+YeQ9apC3RLBfEEam85KjrkDAfE=
script:
  - docker build -t vardantandon/docker-node-travis-example .
  - docker images vardantandon/docker-node-travis-example
before_deploy:
  - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
deploy:
  provider: script
  script: docker push vardantandon/docker-node-travis-example
  on:
    branch: master
